src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

use Cocur\Slugify\Slugify;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{

    const COLOR = [
        'Blonde',
        'Ambrée',
        'Brune',
        'Blanche',
        'Noire',
        'Verte'
    ];

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $style;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $color;

    /**
     * @ORM\Column(type="float")
     */
    private $degrees;

     /**
     * @ORM\Column(type="datetime")
     */
    private $updated_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $new;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $promo;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Picture", mappedBy="product", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /**
     * @Assert\All(
     *     {@Assert\Image(mimeTypes="image/jpeg")})
     */
    private $picturesFiles;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Comment", mappedBy="product")
     */
    private $comments;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\OrderProduct", mappedBy="product", orphanRemoval=true)
     */
    private $orderProducts;

    /**
     * @ORM\Column(type="boolean")
     */
    private $soldOut;

    /**
     * @ORM\Column(type="integer")
     */
    private $IBU;


    public function __construct()
    {
        $this->pictures = new ArrayCollection();
        $this->comments = new ArrayCollection();
        $this->new = false;
        $this->orderProducts = new ArrayCollection();
        $this->updated_at = new \DateTime('now');
    }

    /**
     * @return int|null
     */
    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return string|null
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    public function getSlug()
    {
        return (new Slugify())->slugify($this->getName());
    }

    /**
     * @param string $name
     * @return Product
     */
    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * @param string|null $title
     * @return Product
     */
    public function setTitle(?string $title): self
    {
        $this->title = $title;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * @param string $description
     * @return Product
     */
    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return float|null
     */
    public function getPrice(): ?float
    {
        return $this->price;
    }

    /**
     * @param float $price
     * @return Product
     */
    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getQuantity(): ?int
    {
        return $this->quantity;
    }

    /**
     * @param int $quatity
     * @return Product
     */
    public function setQuantity(int $quantity): self
    {
        $this->quantity = $quantity;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getStyle(): ?string
    {
        return $this->style;
    }

    /**
     * @param string $style
     * @return Product
     */
    public function setStyle(string $style): self
    {
        $this->style = $style;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getColor(): ?string
    {
        return $this->color;
    }

    /**
     * @param string $color
     * @return Product
     */
    public function setColor(string $color): self
    {
        $this->color = $color;

        return $this;
    }

    /**
     * @return float|null
     */
    public function getDegrees(): ?float
    {
        return $this->degrees;
    }

    /**
     * @param float $degrees
     * @return Product
     */
    public function setDegrees(float $degrees): self
    {
        $this->degrees = $degrees;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeInterface $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getNew(): ?bool
    {
        return $this->new;
    }

    public function setNew(bool $new): self
    {
        $this->new = $new;

        return $this;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setProduct($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->contains($picture)) {
            $this->pictures->removeElement($picture);
            // set the owning side to null (unless already changed)
            if ($picture->getProduct() === $this) {
                $picture->setProduct(null);
            }
        }

        return $this;
    }

    public function getPicture(): ?Picture
    {
        if($this->pictures->isEmpty())
        {
            return null;
        }

        return $this->pictures->first();
    }

    /**
     * @return mixed
     */
    public function getPicturesFiles()
    {
        return $this->picturesFiles;
    }

    /**
     * @param mixed $picturesFiles
     * @return Product
     */
    public function setPicturesFiles($picturesFiles)
    {
        foreach ($picturesFiles as $picturesFile)
        {
           $picture = new Picture();
           $picture->setImageFile($picturesFile);
           $this->addPicture($picture);
        }
        $this->picturesFiles = $picturesFiles;
        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setProduct($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getProduct() === $this) {
                $comment->setProduct(null);
            }
        }

        return $this;
    }
    public function getComment(): ?Comment
    {
        if($this->comments->isEmpty())
        {
            return null;
        }

        return $this->comments->first();
    }

    public function getPromo(): ?int
    {
        return $this->promo;
    }

    public function setPromo(?int $promo): self
    {
        $this->promo = $promo;

        return $this;
    }

    /**
     * @return Collection|OrderProduct[]
     */
    public function getOrderProducts(): Collection
    {
        return $this->orderProducts;
    }

    public function addOrderProduct(OrderProduct $orderProduct): self
    {
        if (!$this->orderProducts->contains($orderProduct)) {
            $this->orderProducts[] = $orderProduct;
            $orderProduct->setProduct($this);
        }

        return $this;
    }

    public function removeOrderProduct(OrderProduct $orderProduct): self
    {
        if ($this->orderProducts->contains($orderProduct)) {
            $this->orderProducts->removeElement($orderProduct);
            // set the owning side to null (unless already changed)
            if ($orderProduct->getProduct() === $this) {
                $orderProduct->setProduct(null);
            }
        }

        return $this;
    }

    public function __toString()
    {
        return $this->getName();
    }

    public function getSoldOut(): ?bool
    {
        return $this->soldOut;
    }

    public function setSoldOut(bool $soldOut): self
    {
        $this->soldOut = $soldOut;

        return $this;
    }

    public function getIBU(): ?int
    {
        return $this->IBU;
    }

    public function setIBU(int $IBU): self
    {
        $this->IBU = $IBU;

        return $this;
    }
}

src/Form/ProductType.php
<?php

namespace App\Form;

use App\Entity\Product;
use App\Repository\ProductRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\RangeType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductType extends AbstractType
{
    private $repo;

    public function __construct(ProductRepository $repo)
    {
        $this->repo = $repo;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class,[
               'attr' => ['placeholder' => 'Entrer votre nom...']
            ])
            ->add('title',TextType::class)
            ->add('description', TextareaType::class, [
                'attr' => ['rows' => 8]
            ])
            ->add('price', NumberType::class)
            ->add('quantity', IntegerType::class)
            ->add('style', TextType::class)
            ->add('color', ChoiceType::class,[
                'choices' => $this->getChoicesColor()
            ])
            ->add('degrees', NumberType::class, [
                'attr' => [
                    'min' => 0,
                    'max' => 20
                ]
            ])
            ->add('picturesFiles', FileType::class,[
                'required' => false,
                'multiple' => true
            ])
            ->add('new', CheckboxType::class,[
                'required' => false
            ])
            ->add('promo', IntegerType::class, [
                'required' => false
            ])
            ->add('soldOut', CheckboxType::class, [
                'required' => false
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Product::class,
            'translation_domain' => 'forms'
        ]);
    }

    public function getChoicesColor()
    {
        $output = [];

        foreach (Product::COLOR as $key => $value)
        {
            $output[$value] = $key;
        }

        return $output;
    }

}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Entity\OrderProduct;
use App\Entity\Product;
use App\Form\CommentType;
use App\Repository\ProductRepository;
use App\Repository\CommentRepository;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Doctrine\Common\Persistence\ObjectManager;
use Symfony\Component\HttpFoundation\Session\Session;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use function mysql_xdevapi\getSession;

class ProductController extends AbstractController
{
    /**
     * @var ProductRepository
     */
    private $repoProduct;
    /**
     * @var CommentRepository
     */
    private $repoComment;
    /**
     * @var ObjectManager
     */
    private $em;


    public function __construct(ProductRepository $repoProduct, CommentRepository $repoComment, ObjectManager $em)
    {
        $this->repoProduct = $repoProduct;
        $this->repoComment = $repoComment;
        $this->em = $em;
    }

    /**
     * @Route("/presentation" , name="product.index")
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request)
    {

        $paginator = $paginator->paginate($this->repoProduct->findAllQuery(), $request->query->getInt('page', 1), 6);

        return $this->render('product/index.html.twig', [
            'current_menu' => 'presentation',
            'products' => $paginator
        ]);
    }

    /**
     * @Route("/produits/{slug}-{id}", name="product.show", requirements={"slug": "[a-z0-9\-]*"})
     * @return Response
     */
    public function show(Product $product, string $slug, Request $request, PaginatorInterface $paginator)
    {

        if ($slug !== $product->getSlug()) {
            return $this->redirectToRoute('product.show', [
                'id' => $product->getId(),
                'slug' => $product->getSlug()
            ], 301);
        }
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);

        $product = $this->repoProduct->find($product->getId());
        $paginator = $paginator->paginate($this->repoComment->findAllQuery($product), $request->query->getInt('page', 1), 5);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $comment->setProduct($product);
            $this->em->persist($comment);
            $this->em->flush();
            $this->addFlash('success', 'Votre commentaire a bien été pris en compte');
            //$paginator = $paginator->paginate($this->repoComment->findAllQuery($product), $request->query->getInt('page', 1 ), 5);

            $this->redirectToRoute('product.show', [
                'id' => $product->getId(),
                'slug' => $product->getSlug(),
                'comments' => $paginator
            ]);
        }

        $disable = false;
        if (!empty($request->getSession()->get('caddy'))) {
            $caddy = $request->getSession()->get('caddy');
            foreach ($caddy as $key => $value) {
                if($product->getId() === $value->getProduct()->getId()){
                    $disable = true;
                }
            }
        }

        return $this->render('product/show.html.twig', [
            'product' => $product,
            'comments' => $paginator,
            'disable' => $disable,
            'form_comment' => $form->createView()
        ]);

    }

    /**
     * @Route("/produits/reserver/{id}", name="product.add", methods={"POST|GET"})
     * @param Product $product
     * @param Request $request
     * @return JsonResponse
     */
    public function add(Product $product, Request $request)
    {
        $data = json_decode($request->getContent(), true);

        $orderProd = new OrderProduct();
        $orderProd->setProduct($product);
        $orderProd->setQuantity($data['qteReserve']);

        $session = $request->getSession();

        if (empty($session->getName('caddy'))) {
            $session->set('caddy', []);
        }

        $caddy = $session->get('caddy');
        $caddy[] = $orderProd;
        $session->set('caddy', $caddy);

        return new JsonResponse(['success' => count($session->get('caddy'))]);


    }


}

templates/product/_product.html.twig
{#{% cache 'product' ~ product.id product.updatedAt.timestamp %}#}

    {% if product.soldOut %}
        <div class="col-md-4">
            <div class="card mt-4 soldout">
                <h4 class="card-header">
                    SOLD OUT
                </h4>
                <div class="card-body">
                    {% if product.picture %}
                        <img src="{{ vich_uploader_asset(product.picture, 'imageFile') }}" class="card-img-top">
                    {% else %}
                        <img src="{{ asset('images/empty.jpg') }}" alt="" class="card-img-top">
                    {% endif %}
                    <div class="card-text mt-2">
                        <h5> {{ product.title }}</h5>

                        {% if product.promo %}
                            <p class="text-right" style="text-decoration: line-through">
                                <strong>{{ (product.price)|number_format(2, ',', '.') }}€</strong>
                            </p>
                            <p class="text-right">
                                <strong>{{ (product.price - (product.price * product.promo)/100)|number_format(2,',', '.') }}
                                    €</strong>
                            </p>
                            <span class="ribbon bottom-left ribbon-danger">
                                 <small>Promo :  -{{ product.promo }}%</small>
                             </span>
                        {% else %}
                            <p class="text-right">
                                <strong>{{ product.price|number_format(2, ',', '.') }}€</strong>
                            </p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>

    {% else %}
        <div class="col-md-4">
            <div class="card mt-4">
                <h4 class="card-header"><a
                            href="{{ path('product.show', {'slug': product.slug ,'id': product.id}) }}">{{ product.name }}</a>
                </h4>
                {% if product.new %}
                    <span class="ribbon top-right ribbon-success">
                          <small>NEWS</small>
                      </span>
                {% endif %}
                <div class="card-body">
                    {% if product.picture %}
                        <a href="{{ path('product.show', {'slug': product.slug ,'id': product.id}) }}"><img
                                    src="{{ vich_uploader_asset(product.picture, 'imageFile') }}" alt=""
                                    class="card-img-top"></a>
                    {% else %}
                        <a href="{{ path('product.show', {'slug': product.slug , 'id': product.id}) }}"><img
                                    src="{{ asset('images/empty.jpg') }}" alt="" class="card-img-top"></a>
                    {% endif %}
                    <div class="card-text mt-2">
                        <h5> {{ product.title }}</h5>

                        {% if product.promo %}
                            <p class="text-right" style="text-decoration: line-through">
                                <strong>{{ (product.price)|number_format(2, ',', '.') }}€</strong>
                            </p>
                            <p class="text-right">
                                <strong>{{ (product.price - (product.price * product.promo)/100)|number_format(2,',', '.') }}
                                    €</strong>
                            </p>
                            <span class="ribbon bottom-left ribbon-danger">
                                 <small>Promo :  -{{ product.promo }}%</small>
                             </span>
                        {% else %}
                            <p class="text-right">
                                <strong>{{ product.price|number_format(2, ',', '.') }}€</strong>
                            </p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endif %}

{#{% endcache %}#}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title 'Présentation de la brasserie' %}

 {% block body %}
     <h1>Nos produits</h1>

     <div class="alert alert-danger">
         Attention, tous nos produits sont à retirer en magasin
     </div>
     <div class="row">
         {% for product in products %}
            {{ include('product/_product.html.twig') }}
         {% endfor %}
     </div>

     <div class="navigation mt-4 d-flex justify-content-center">
         {{ knp_pagination_render(products) }}
     </div>
 {% endblock %}

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title %} {{ product.name }} {% endblock %}

{% block body %}


     <div class="jumbotron text-center mt-4">
         <div class="row">
             <div class="col-md-8">
                 {% if product.pictures is empty %}
                     <img src="{{ asset('images/empty.jpg') | imagine_filter('my_medium') }}" alt="">
                 {% else %}
                     <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
                         <div class="carousel-inner">
                             {% for picture in product.pictures %}
                                 <div class="carousel-item {% if loop.first %} active {% endif %}">
                                     <img src="{{ vich_uploader_asset(picture, 'imageFile')| imagine_filter('my_medium') }}"
                                          style="width: 70%;height: auto" alt="card-img-top">
                                 </div>
                             {% endfor %}
                         </div>
                         <a class="carousel-control-prev" href="#carouselExampleControls" role="button"
                            data-slide="prev">
                             <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                             <span class="sr-only">Previous</span>
                         </a>
                         <a class="carousel-control-next" href="#carouselExampleControls" role="button"
                            data-slide="next">
                             <span class="carousel-control-next-icon" aria-hidden="true"></span>
                             <span class="sr-only">Next</span>
                         </a></div>
                 {% endif %}
             </div>
             <div class="col-md-4">
                 <h1>{{ product.name }}</h1>
                 <h3><strong>{{ product.price }} €</strong></h3>
                 <div class="input-group align-items-end">

                    {#      button group         #}
                     <div class="input-group {%  if disable %} disabled {% endif %}">
                         <select class="custom-select" id="qteReserve">
                             <option value="1" selected>1</option>
                             <option value="2">2</option>
                             <option value="3">3</option>
                             <option value="4">4</option>
                             <option value="5">5</option>
                         </select>
                         <div class="input-group-append">
                             <a href="{{ path('product.add', {id: product.id}) }}" data-reserve id="button-addon2"
                                data-token="{{ csrf_token('reserve' ~ product.id) }}" class="btn btn-outline-secondary {% if disable %} disabled {% endif %}" method="GET">Réserver</a>
                         </div>
                     </div>
                     {#                     #}

                     {% if is_granted("ROLE_ADMIN") %}
                         <a class="btn btn-secondary" href="{{ path('admin.product.edit', {'id': product.id}) }}">Éditer</a>
                     {% endif %}
                 </div>
             </div>
         </div>

     </div>

     <div class="row">
         <div class="col-md-6">
             <table class="table table-striped">
                 <thead class="thead-dark">
                 <tr>
                     <th>Nom</th>
                     <td>{{ product.name }}</td>
                 </tr>
                 <tr>
                     <th>Title</th>
                     <td>{{ product.title }}</td>
                 </tr>
                 <tr>
                     <th>Style</th>
                     <td>{{ product.style }}</td>
                 </tr>
                 <tr>
                     <th>Couleur</th>
                     <td>{{ product.color }}</td>
                 </tr>
                 <tr>
                     <th>Degrès</th>
                     <td>{{ product.degrees }}</td>
                 </tr>
                 </thead>
             </table>
         </div>
         <div class="col-md-6">
             <h4>Description</h4>
             <p>{{ product.description }}</p>


         </div>
     </div>

     <h2>Commentaires</h2>
     <div class="row">
         <div class="col">
             {{ form_start(form_comment) }}
             {{ form_widget(form_comment) }}
             <div class="row">
                 <label for="notesA">Notes : </label>
                 <div class="items-wrap">
                     <div class="item-star">
                         {% for i in 1..10 %}
                             <input id="star-row{{ i }}-col-{{ i }}" name="star-row{{ i }}" type="radio"
                                    value="{{ 6 - i }}"/>
                             <label for="star-row{{ i }}-col-{{ i }}">
                                 <i class="ion-beer"></i>
                             </label>
                         {% endfor %}
                     </div>
                 </div>
                 <br>
             </div>
             <div class="row">
                 <input type="submit" value="Commenter" class="btn btn-primary">
             </div>

             {{ form_end(form_comment) }}
         </div>
     </div>

     {% for comment in comments if comments is not empty %}
         <div class="row mt-3">
             <div class="col-md-3">
                 <div class="card">
                     <div class="card-header">
                         {{ comment.pseudo }}
                     </div>
                     <div class="card-body">
                         {{ comment.message }}<br>
                         {{ comment.note }}
                     </div>
                 </div>
             </div>
         </div>
     {% endfor %}

     <div class="navigation mt-4 d-flex justify-content-center">
         {{ knp_pagination_render(comments) }}
     </div>

 {% endblock %}